### ISSUE TITLE
邀请函

### ISSUE THREAD

**Issue by CSDAIZUO** [sailordiary/B62010Y-B62011Y-COS318-UCAS#1]
看到你的github repo，我印象深刻。
现邀请你 150rmb/h 开发跨平台单机逻辑计算系统 
时间为一学期
涉及到C语言网络编程 前端用python搭建框架
有兴趣可联系我了解项目需求 谢谢

**Comment by sailordiary** [comment]
兄弟你太有创意了
我能摸摸你的奖杯吗

**Comment by CSDAIZUO** [comment]
无功不受禄 哪来的奖杯
